import pulp as PLP
import numpy as np
from modeller.pakning.generalized_assignment_problem import generalized_assignment_problem

def local_search(inbound_trucks,
                 outbound_trucks,
                 inbound_doors,
                 outbound_doors,
                 inbound_doors_cap,
                 outbound_doors_cap,
                 distance_matrix,
                 volume_flow_matrix,
                 max_iter = 5,
                 initial_outbound = None):
    """This function implements a local search heuristic for the CDAP from uge 18 Crossdocking.
    The local search is based on the idea of swapping the assignments of two trucks
    (one inbound and one outbound) and checking if the new solution
    is better than the current solution. If it is, we accept the new solution and continue
    searching for better solutions. If not, we reject the new solution
    and continue searching for better solutions.

    initial_outbound : initial outbound solution pulp variable - this can be generated by selecting a random door for each truck
    inbound_trucks : range of inbound trucks
    outbound_trucks : range of outbound trucks
    inbound_doors : range of inbound doors
    outbound_doors : range of outbound doors
    inbound_doors_cap : list of capacities for each inbound door
    outbound_doors_cap : list of capacities for each outbound door
    distance_matrix : 2D matrix of distances between inbound and outbound doors
    volume_flow_matrix : 2D matrix of volumes between inbound trucks and outbound trucks
    """
    M = inbound_trucks
    N = outbound_trucks
    I = inbound_doors
    J = outbound_doors
    S = inbound_doors_cap
    R = outbound_doors_cap
    d = distance_matrix
    v = volume_flow_matrix
    total_inbound = [sum([v[m][n] for n in N]) for m in M]
    total_outbound = [sum([v[m][n] for m in M]) for n in N]
    # Best know solution
    B = 10**10 # This is a very large number, we want to minimize the objective value



    # The weight of assigning truck m to door i is the total volume of what truck m has to deliver.
    # This is used in the GAP
    weights_x = np.zeros((len(M), len(I)))
    for m in M:
        for i in I:
            weights_x[m][i] = total_inbound[m]


    # Same for truck n to door j
    weights_y = np.zeros((len(N), len(J)))
    for n in N:
        for i in J:
            weights_y[n][i] = total_outbound[n]
    # Dummy for best solution
    best_x = None
    best_y = None

    # Construct profit matrix for the GAPs
    profit_x = np.zeros((len(M), len(I)))
    profit_y = np.zeros((len(N), len(J)))

    def optimize_x(y_hat):
        # Gap for optimizing x, where weights are unitary for each truck and bounded by the inbound door capacities.
        for m in M:
            for i in I:
                profit_x[m, i] = sum([y_hat[n][j].varValue * v[m][n] * d[i][j]
                                      for n in N for j in J if y_hat[n][j].varValue is not None])
        gap_x = generalized_assignment_problem(profit_x, weights_x, S)
        gap_x.construct_constraints()
        gap_x.solve_and_print(print_sol= False)

        return gap_x.x

    def optimize_y(x_hat):
        # Similar GAP for optimizing y
        for n in N:
            for j in J:
                profit_y[n,j] = sum([x_hat[m][i].varValue * v[m][n] * d[i][j]
                                     for m in M for i in I if x_hat[m][i].varValue is not None])
        gap_y = generalized_assignment_problem(profit_y, weights_y, R)
        gap_y.construct_constraints()
        gap_y.solve_and_print(print_sol= False)
        return gap_y.x

    def compute_new_objective(x_hat, y_hat):
        z = 0
        for m in M:
            for i in I:
                for n in N:
                    for j in J:
                        if y_hat[n][j].varValue is not None and x_hat[m][i].varValue is not None:
                            z += d[i][j]*v[m][n]*x_hat[m][i].varValue*y_hat[n][j].varValue
        return z

    for _ in range(max_iter):
        # Start at a random assignment for y_hat for every iteration
        prev_z = 10**10
        if initial_outbound is None:
            y_hat = PLP.LpVariable.dicts("y_hat", indices=(N, J), cat=PLP.LpBinary)
            lst = np.zeros(len(J)*len(N), dtype=int)
            lst[np.random.choice(len(J)*len(N), len(N), replace=False)] = 1
            i = 0
            for n in N:
                for j in J:
                    y_hat[n][j].setInitialValue(lst[i])
                    i = i + 1


        else:
            y_hat = initial_outbound
        # Local search
        while True:
            x_hat = optimize_x(y_hat)
            y_hat = optimize_y(x_hat)
            z = compute_new_objective(x_hat, y_hat)
            if z < B:
                B = z
                best_x = x_hat
                best_y = y_hat
            if z >= prev_z:

                break

            prev_z = z
    return B, best_x, best_y

if __name__ == "__main__":
    inbound_trucks = range(3)
    outbound_trucks = range(4)
    inbound_doors = range(3)
    outbound_doors = range(4)
    inbound_doors_cap = [8,8,8]
    outbound_doors_cap = [6,6,6,6]

    distance_matrix = [
        [2,2,6,10], # Distances from I1
        [6,2,2, 6], # -              I2
        [10,6,2, 2]] # -              I3

    volume_flow_matrix = [
        [2,0,2,1], # Flow from IT1
        [1,2,2,1], # -         IT2
        [1,1,0,3]] # -         IT3

    best_sol, x , y = local_search(inbound_trucks,
                                   outbound_trucks,
                                   inbound_doors,
                                   outbound_doors,
                                   inbound_doors_cap,
                                   outbound_doors_cap,
                                   distance_matrix,
                                   volume_flow_matrix)
    print("Best solution found:", best_sol)









